### ISSUE TITLE
[Feature request] Enhance mu4e-view-save-all-attachments.el for attachments with the same name

### ISSUE THREAD

**Issue by jpggithub** [sje30/emacs#1]
Hi
First of all, many thanks for your extremely useful code for saving all attachments in a mail with mu4 :-)
Can you please enhance it to manage several files in a mail that have the same name? 

It rarely happens but some people in my office send mails with several files with the same name but not the same content.
Your actual code save only one file instead of saving all the files.

For instance, if the mail contains the files:
filename.pdf
filename.pdf
filename.pdf

the files  saved could be renamed as
filename.pdf
filename-1.pdf
filename-2.pdf

**Comment by sje30** [comment]
happy to take a look, but could you send me an example email to work on?  (sje30 @ cam . ac . uk )

**Comment by jpggithub** [comment]
Thanks, it works perfectly!

Perhaps you could delete the following lines or at least puitting them at the very beginning of your code:
```
;;;  mnemnonic: > is to redirect the files to output everything.
;;(define-key mu4e-view-mode-map ">" 'mu4e-view-save-all-attachments)
```
It can delete some configuration of your users so it is important that they see this binding when they take your code

**Comment by sje30** [comment]
> Perhaps you could delete the following lines or at least puitting them
> at the very beginning of your code:
>
> ;;;  mnemnonic: > is to redirect the files to output everything.
> ;;(define-key mu4e-view-mode-map ">" 'mu4e-view-save-all-attachments)

good idea, thank you.  Done.
